server.port: 8080

spring:
  main:
    banner-mode: "off"
  application:
    name: ${nais.app.name:fp-infotrygd-foreldrepenger}
  datasource:
    url: ${defaultds.url}
    username: ${defaultds.username}
    password: ${defaultds.password}
    driver-class-name: ${defaultds.driver:oracle.jdbc.OracleDriver}
  jpa:
    hibernate:
      ddl-auto: ${app.ddl.auto:none}
    properties:
      hibernate:
        default_schema: ${defaultds.schema}
        jdbc:
          fetch_size: 50
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${azure.openid.config.issuer}
          audiences:
            - ${azure.app.client.id}

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false

# Brukes til entra discovery og jwks
entra:
  proxy: https://webproxy-nais.nav.no:8088
