server.port: 8080

spring:
  main:
    banner-mode: "off"
  cloud.discovery.client.health-indicator.enabled: false
  application:
    name: ${NAIS_APP_NAME:fp-infotrygd-foreldrepenger}
  datasource:
    url: ${DEFAULTDS_URL}
    username: ${DEFAULTDS_USERNAME}
    password: ${DEFAULTDS_PASSWORD}
    driver-class-name: ${DEFAULTDS_DRIVER:oracle.jdbc.OracleDriver}
  jpa:
    hibernate:
      ddl-auto: ${APP_DDL_AUTO:none}
    properties:
      hibernate:
        default_schema: ${DEFAULTDS_SCHEMA}
        jdbc:
          fetch_size: 50
    open-in-view: false

springdoc:
  packages-to-scan: no.nav.infotrygd.foreldrepenger
  swagger-ui:
    enabled: false
    disable-swagger-default-url: true
  api-docs:
      enabled: false

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false

#oidc...
http.proxy.parametername: notused

no.nav.security.jwt:
  expirythreshold: 60 #threshold in minutes until token expires
  issuer:
    azure:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      proxyurl: ${HTTPS_PROXY}
