--------------------------------------------------
-- Create Table INFOTRYGD_Q0.SA_SAK_10
--------------------------------------------------
Create table INFOTRYGD_Q0.SA_SAK_10
(
    S01_PERSONKEY          BIGINT                                                     NOT NULL,
    S05_SAKSBLOKK          CHAR(1)                                                    NOT NULL,
    S10_SAKSNR             CHAR(2)                                                    NOT NULL,
    S10_REG_DATO           BIGINT                                                     NOT NULL,
    S10_MOTTATTDATO        BIGINT                                                     NOT NULL,
    S10_KAPITTELNR         CHAR(2)                                                    NOT NULL,
    S10_VALG               CHAR(2)                                                    NOT NULL,
    S10_UNDERVALG_1        CHAR(1)                                                    NOT NULL,
    S10_UNDERVALG_2        CHAR(1)                                                    NOT NULL,
    S10_DUBLETT_FEIL       CHAR(1)                                                    NOT NULL,
    S10_TYPE               CHAR(2)                                                    NOT NULL,
    S10_INNSTILLING        CHAR(2)                                                    NOT NULL,
    S10_RESULTAT           CHAR(2)                                                    NOT NULL,
    S10_NIVAA              CHAR(3)                                                    NOT NULL,
    S10_INNSTILLDATO       BIGINT                                                     NOT NULL,
    S10_VEDTAKSDATO        BIGINT                                                     NOT NULL,
    S10_IVERKSATTDATO      BIGINT                                                     NOT NULL,
    S10_GRUNNBL_DATO       BIGINT                                                     NOT NULL,
    S10_AARSAKSKODE        CHAR(2)                                                    NOT NULL,
    S10_TELLEPUNKT         CHAR(3)                                                    NOT NULL,
    S10_TELLETYPE          CHAR(1)                                                    NOT NULL,
    S10_TELLEDATO          BIGINT                                                     NOT NULL,
    S10_EVAL_KODE          CHAR(4)                                                    NOT NULL,
    S10_EVAL_TIR           CHAR(1)                                                    NOT NULL,
    S10_FREMLEGG           CHAR(3)                                                    NOT NULL,
    S10_INNSTILLING2       CHAR(2)                                                    NOT NULL,
    S10_INNSTILLDATO2      BIGINT                                                     NOT NULL,
    S10_ANNEN_INSTANS      CHAR(1)                                                    NOT NULL,
    S10_BEHEN_TYPE         CHAR(3)                                                    NOT NULL,
    S10_BEHEN_ENHET        CHAR(4)                                                    NOT NULL,
    S10_REG_AV_TYPE        CHAR(3)                                                    NOT NULL,
    S10_REG_AV_ENHET       CHAR(4)                                                    NOT NULL,
    S10_DIFF_FRAMLEGG      CHAR(3)                                                    NOT NULL,
    S10_INNSTILLT_AV_TYPE  CHAR(3)                                                    NOT NULL,
    S10_INNSTILLT_AV_ENHET CHAR(4)                                                    NOT NULL,
    S10_VEDTATT_AV_TYPE    CHAR(3)                                                    NOT NULL,
    S10_VEDTATT_AV_ENHET   CHAR(4)                                                    NOT NULL,
    S10_PRIO_TAB           CHAR(6)                                                    NOT NULL,
    S10_AOE                CHAR(3)                                                    NOT NULL,
    S10_ES_SYSTEM          CHAR(1)                                                    NOT NULL,
    S10_ES_GSAK_OPPDRAGSID BIGINT                                                     NOT NULL,
    S10_KNYTTET_TIL_SAK    CHAR(2)                                                    NOT NULL,
    S10_VEDTAKSTYPE        CHAR(1)                                                    NOT NULL,
    S10_REELL_ENHET        CHAR(4)                                                    NOT NULL,
    S10_MOD_ENDRET         CHAR(1)                                                    NOT NULL,
    TK_NR                  CHAR(4)                                                    NOT NULL,
    F_NR                   CHAR(11)                                                   NOT NULL,
    OPPRETTET              TIMESTAMP(6) DEFAULT current_timestamp                     NOT NULL,
    ENDRET_I_KILDE         TIMESTAMP(6) DEFAULT current_timestamp                     NOT NULL,
    KILDE_IS               VARCHAR(12) DEFAULT ' '                                    NOT NULL,
    REGION                 CHAR(1)      DEFAULT ' '                                   NOT NULL,
    ID_SAK                 BIGINT       DEFAULT                                       NOT NULL  --sekvens
);

--------------------------------------------------
-- Create Table INFOTRYGD_Q0.SA_STATUS_15
--------------------------------------------------
Create table INFOTRYGD_Q0.SA_STATUS_15
(
    S01_PERSONKEY       BIGINT                                                     NOT NULL,
    S05_SAKSBLOKK       CHAR(1)                                                    NOT NULL,
    S10_SAKSNR          CHAR(2)                                                    NOT NULL,
    S15_LOPENR          CHAR(2)                                                    NOT NULL,
    S15_BEH_ENHET_TYPE  CHAR(3)                                                    NOT NULL,
    S15_BEH_ENHET_ENHET CHAR(4)                                                    NOT NULL,
    S15_STATUS          CHAR(2)                                                    NOT NULL,
    S15_STATUS_DATO     BIGINT                                                     NOT NULL,
    S15_BRUKERID        CHAR(7)                                                    NOT NULL,
    S15_STATUS_KLOKKE   CHAR(6)                                                    NOT NULL,
    S15_STATUS_BRUKERID CHAR(7)                                                    NOT NULL,
    S15_ENDRINGS_KODE   CHAR(1)                                                    NOT NULL,
    S15_TYPE_GML        CHAR(2)                                                    NOT NULL,
    S15_TYPE_NY         CHAR(2)                                                    NOT NULL,
    S15_LOVETSVAR_DATO  BIGINT                                                     NOT NULL,
    S15_ANT_LOFTER      CHAR(2)                                                    NOT NULL,
    S15_GRUPPE          CHAR(2)                                                    NOT NULL,
    S15_SPERR           CHAR(1)                                                    NOT NULL,
    TK_NR               CHAR(4)                                                    NOT NULL,
    F_NR                CHAR(11)                                                   NOT NULL,
    OPPRETTET           TIMESTAMP(6) DEFAULT current_timestamp                     NOT NULL,
    ENDRET_I_KILDE      TIMESTAMP(6) DEFAULT current_timestamp                     NOT NULL,
    KILDE_IS            VARCHAR(12) DEFAULT ' '                                    NOT NULL,
    REGION              CHAR(1)      DEFAULT ' '                                   NOT NULL,
    ID_STATUS           BIGINT       DEFAULT                                       NOT NULL  --sekvens
);
