package no.nav.infotrygd.foreldrepenger.model.kodeverk

enum class SakResultat(override val kode: String, override val tekst: String) : Kode {
    BESLUT("?", "Beslutningsstøtte"),
    A("A", "Avslag"),
    AG("AG", "Avslag godkjent"),
    AK("AK", "Avvist klage"),
    AV("AV", "Advarsel"),
    DG("DG", "Delvis godkjent"),
    DI("DI", "Delvis innvilget"),
    DT("DT", "Delvis tilbakebetale"),
    FB("FB", "Ferdigbehandlet"),
    FI("FI", "Fortsatt innvilget"),
    GK("GK", "Godkjent"),
    H("H", "Henlagt / trukket tilbake"),
    HB("HB", "Henlagt / bortfalt"),
    I("I", "Innvilget"),
    IB("IB", "Ikke behandlet"),
    IN("IN", "Innvilget ny situasjon"),
    IS("IS", "Ikke straffbart"),
    IT("IT", "Ikke tilbakebetale"),
    MO("MO", "Midlertidig opphørt"),
    MT("MT", "Mottatt"),
    NB("NB", "Hjemsendt ny behandling"),
    O("O", "Opphørt"),
    PA("PA", "Politianmeldelse"),
    R("R", "Redusert"),
    SB("SB", "Sak i bero"),
    TB("TB", "Tilbakebetale"),
    TH("TH", "Tips henlagt"),
    TO("TO", "Tips oppfølging"),
    Ø("Ø", "Økning"),
    UKJENT_AA("AA", "Ukjent"),
    ÅPEN("  ", "Åpen")
}