name: "Deploy"

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119)'
      cluster:
        required: true
        type: string
        description: 'The cluster to deploy to (dev-fss|dev-gcp|prod-fss|prod-gcp)'
      namespace:
        required: false
        type: string
        description: 'The namespace to deploy to'
        default: 'teamforeldrepenger'
      app:
        required: true
        type: string
        description: 'The app to deploy (foreldrepenger|svangerskapspenger|sykepenger)'

jobs:
  deploy:
    name: deploy
    environment: ${{ inputs.app }}:${{ inputs.cluster }}:${{ inputs.namespace }}
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6.0.3

      - name: Login GAR
        uses: nais/login@d6ab5d83f735e9f155eb9d7d29cd20ae46820ea9 # ratchet:nais/login@v0
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: teamforeldrepenger

      - name: Deploy av fp-infotrygd-${{ inputs.app }} til ${{ inputs.cluster }} fra GAR
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # ratchet:nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: ${{ inputs.cluster }}
          IMAGE: ${{ steps.login.outputs.registry }}/${{ github.repository }}:${{ inputs.image }}
          RESOURCE: .deploy/naiserator.yaml
          VARS: .deploy/${{ inputs.app }}/${{ inputs.cluster }}-${{ inputs.namespace }}.json
